# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6.4-node-browsers
        environment:
          TZ: /usr/share/zoneinfo/Asia/Tokyo
          DB_HOST: 127.0.0.1
          RAILS_ENV: test
      - image: circleci/mysql:5.7
        environment:
          TZ: /usr/share/zoneinfo/Asia/Tokyo
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

    working_directory: ~/circle-ci-example

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install bundler
          command: |
            sudo gem install bundler
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: cp -v config/database.ci.yml config/database.yml
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      - run:
          name: clone repository of rspec
          command: |
            mkdir /tmp/rspec-repository
            cd /tmp/rspec-repository
            git clone https://runteq:$GITHUB_TOKEN@github.com/runteq/runteq_curriculum_normal
            cd /tmp/rspec-repository/runteq_curriculum_normal
            git checkout $CIRCLE_BRANCH
            rm -rf ~/circle-ci-example/spec
            mv /tmp/rspec-repository/runteq_curriculum_normal/spec ~/circle-ci-example/spec

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            cd ~/circle-ci-example
            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format html \
              --out /tmp/test-results/rspec.html \
              --format progress \
              $TEST_FILES

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
